apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: retention-cron
scopes:
  - worker
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 2 * * *"  # Run daily at 2 AM
  - name: route
    value: /jobs/data-retention
