apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sandbox-warning-cron
scopes:
  - worker
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1h"  # Check hourly for warnings
  - name: route
    value: /jobs/sandbox-warnings
