apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: cim
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: akv-cloudinframap
  - name: azureTenantId
    secretKeyRef:
      name: azure-identity
      key: tenant-id
  - name: azureClientId
    secretKeyRef:
      name: azure-identity
      key: client-id
  - name: azureClientSecret
    secretKeyRef:
      name: azure-identity
      key: client-secret

