# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\tcommon.v1\"j\n\x0eRequestContext\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06org_id\x18\x03 \x01(\t\x12\r\n\x05roles\x18\x04 \x03(\t\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\"4\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"_\n\x12PaginationResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x13\n\x0btotal_items\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\"K\n\rBlobReference\x12\x10\n\x08\x62lob_url\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\"4\n\nTimestamps\x12\x12\n\ncreated_at\x18\x01 \x01(\t\x12\x12\n\nupdated_at\x18\x02 \x01(\t*\xd5\x01\n\x10ProcessingStatus\x12!\n\x1dPROCESSING_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19PROCESSING_STATUS_PENDING\x10\x01\x12!\n\x1dPROCESSING_STATUS_IN_PROGRESS\x10\x02\x12\x1f\n\x1bPROCESSING_STATUS_COMPLETED\x10\x03\x12\x1c\n\x18PROCESSING_STATUS_FAILED\x10\x04\x12\x1d\n\x19PROCESSING_STATUS_PARTIAL\x10\x05\x42&\n\"com.reportplatform.proto.common.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.reportplatform.proto.common.v1P\001'
  _globals['_PROCESSINGSTATUS']._serialized_start=428
  _globals['_PROCESSINGSTATUS']._serialized_end=641
  _globals['_REQUESTCONTEXT']._serialized_start=37
  _globals['_REQUESTCONTEXT']._serialized_end=143
  _globals['_PAGINATIONREQUEST']._serialized_start=145
  _globals['_PAGINATIONREQUEST']._serialized_end=197
  _globals['_PAGINATIONRESPONSE']._serialized_start=199
  _globals['_PAGINATIONRESPONSE']._serialized_end=294
  _globals['_BLOBREFERENCE']._serialized_start=296
  _globals['_BLOBREFERENCE']._serialized_end=371
  _globals['_TIMESTAMPS']._serialized_start=373
  _globals['_TIMESTAMPS']._serialized_end=425
# @@protoc_insertion_point(module_scope)
