# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from generator.v1 import generator_pb2 as generator_dot_v1_dot_generator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in generator/v1/generator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PptxGeneratorServiceStub(object):
    """=============================================================================
    PPTX Generator Service
    =============================================================================

    Service for generating PPTX reports
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateReport = channel.unary_unary(
                '/generator.v1.PptxGeneratorService/GenerateReport',
                request_serializer=generator_dot_v1_dot_generator__pb2.PptxGenerateReportRequest.SerializeToString,
                response_deserializer=generator_dot_v1_dot_generator__pb2.PptxGenerateReportResponse.FromString,
                _registered_method=True)
        self.BatchGenerate = channel.unary_unary(
                '/generator.v1.PptxGeneratorService/BatchGenerate',
                request_serializer=generator_dot_v1_dot_generator__pb2.PptxBatchGenerateRequest.SerializeToString,
                response_deserializer=generator_dot_v1_dot_generator__pb2.PptxBatchGenerateResponse.FromString,
                _registered_method=True)


class PptxGeneratorServiceServicer(object):
    """=============================================================================
    PPTX Generator Service
    =============================================================================

    Service for generating PPTX reports
    """

    def GenerateReport(self, request, context):
        """Generate a single PPTX report
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGenerate(self, request, context):
        """Batch generate multiple PPTX reports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PptxGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=generator_dot_v1_dot_generator__pb2.PptxGenerateReportRequest.FromString,
                    response_serializer=generator_dot_v1_dot_generator__pb2.PptxGenerateReportResponse.SerializeToString,
            ),
            'BatchGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGenerate,
                    request_deserializer=generator_dot_v1_dot_generator__pb2.PptxBatchGenerateRequest.FromString,
                    response_serializer=generator_dot_v1_dot_generator__pb2.PptxBatchGenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generator.v1.PptxGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generator.v1.PptxGeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PptxGeneratorService(object):
    """=============================================================================
    PPTX Generator Service
    =============================================================================

    Service for generating PPTX reports
    """

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generator.v1.PptxGeneratorService/GenerateReport',
            generator_dot_v1_dot_generator__pb2.PptxGenerateReportRequest.SerializeToString,
            generator_dot_v1_dot_generator__pb2.PptxGenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generator.v1.PptxGeneratorService/BatchGenerate',
            generator_dot_v1_dot_generator__pb2.PptxBatchGenerateRequest.SerializeToString,
            generator_dot_v1_dot_generator__pb2.PptxBatchGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExcelGeneratorServiceStub(object):
    """=============================================================================
    Excel Generator Service
    =============================================================================

    Service for generating Excel reports
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateReport = channel.unary_unary(
                '/generator.v1.ExcelGeneratorService/GenerateReport',
                request_serializer=generator_dot_v1_dot_generator__pb2.ExcelGenerateReportRequest.SerializeToString,
                response_deserializer=generator_dot_v1_dot_generator__pb2.ExcelGenerateReportResponse.FromString,
                _registered_method=True)
        self.BatchGenerate = channel.unary_unary(
                '/generator.v1.ExcelGeneratorService/BatchGenerate',
                request_serializer=generator_dot_v1_dot_generator__pb2.ExcelBatchGenerateRequest.SerializeToString,
                response_deserializer=generator_dot_v1_dot_generator__pb2.ExcelBatchGenerateResponse.FromString,
                _registered_method=True)
        self.UpdateSheet = channel.unary_unary(
                '/generator.v1.ExcelGeneratorService/UpdateSheet',
                request_serializer=generator_dot_v1_dot_generator__pb2.UpdateSheetRequest.SerializeToString,
                response_deserializer=generator_dot_v1_dot_generator__pb2.UpdateSheetResponse.FromString,
                _registered_method=True)


class ExcelGeneratorServiceServicer(object):
    """=============================================================================
    Excel Generator Service
    =============================================================================

    Service for generating Excel reports
    """

    def GenerateReport(self, request, context):
        """Generate a single Excel report
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGenerate(self, request, context):
        """Batch generate multiple Excel reports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSheet(self, request, context):
        """Update a single sheet in an existing Excel workbook (preserves all other sheets)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExcelGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=generator_dot_v1_dot_generator__pb2.ExcelGenerateReportRequest.FromString,
                    response_serializer=generator_dot_v1_dot_generator__pb2.ExcelGenerateReportResponse.SerializeToString,
            ),
            'BatchGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGenerate,
                    request_deserializer=generator_dot_v1_dot_generator__pb2.ExcelBatchGenerateRequest.FromString,
                    response_serializer=generator_dot_v1_dot_generator__pb2.ExcelBatchGenerateResponse.SerializeToString,
            ),
            'UpdateSheet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSheet,
                    request_deserializer=generator_dot_v1_dot_generator__pb2.UpdateSheetRequest.FromString,
                    response_serializer=generator_dot_v1_dot_generator__pb2.UpdateSheetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generator.v1.ExcelGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generator.v1.ExcelGeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExcelGeneratorService(object):
    """=============================================================================
    Excel Generator Service
    =============================================================================

    Service for generating Excel reports
    """

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generator.v1.ExcelGeneratorService/GenerateReport',
            generator_dot_v1_dot_generator__pb2.ExcelGenerateReportRequest.SerializeToString,
            generator_dot_v1_dot_generator__pb2.ExcelGenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generator.v1.ExcelGeneratorService/BatchGenerate',
            generator_dot_v1_dot_generator__pb2.ExcelBatchGenerateRequest.SerializeToString,
            generator_dot_v1_dot_generator__pb2.ExcelBatchGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSheet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generator.v1.ExcelGeneratorService/UpdateSheet',
            generator_dot_v1_dot_generator__pb2.UpdateSheetRequest.SerializeToString,
            generator_dot_v1_dot_generator__pb2.UpdateSheetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
