package com.reportplatform.audit.model.enums;

public enum AuditAction {
    FILE_UPLOADED,
    DATA_CHANGED,
    ROLE_CHANGED,
    REPORT_STATUS_CHANGED,
    FORM_SUBMITTED,
    FORM_FIELD_CHANGED,
    FORM_COMMENT_ADDED,
    FORM_IMPORT_CONFIRMED,
    DOCUMENT_VIEWED,
    AI_PROMPT_SENT,
    VERSION_CREATED,
    USER_LOGIN,
    USER_LOGOUT
}
