# Dapr PubSub configuration for engine-data
# engine-data: ms-sink-tbl + ms-sink-doc + ms-sink-log + ms-qry + ms-dash + ms-srch + ms-tmpl
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reportplatform-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
    - name: consumerGroup
      value: engine-data-group
