#!/usr/bin/env python3
# UAT Report Generator
# Reads all *.log files from the logs/ directory and generates UAT_REPORT.md
# with a summary table: step, total tests, passed, failed, success %.

import os
import re
import sys
import datetime

LOGS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../logs")


def parse_log_file(filepath: str) -> dict:
    """Parse a .log file and extract step name, pass/fail counts."""
    step_name = os.path.splitext(os.path.basename(filepath))[0]
    passed = 0
    failed = 0
    missing_features = 0

    try:
        raw = open(filepath, "rb").read()
        # Detect encoding: UTF-16 LE/BE BOM, UTF-8 BOM, or plain UTF-8
        if raw[:2] in (b"\xff\xfe", b"\xfe\xff"):
            content = raw.decode("utf-16")
        elif raw[:3] == b"\xef\xbb\xbf":
            content = raw[3:].decode("utf-8")
        else:
            content = raw.decode("utf-8", errors="replace")

        # Count markers from log lines
        passed = len(re.findall(r"\[OK\]", content))
        failed = len(re.findall(r"\[FAIL\]", content))
        skipped = len(re.findall(r"\[SKIP\]", content))

        # Try to extract from summary block (more accurate — counters are
        # authoritative because missing_feature() reclassifies FAIL→SKIP)
        m = re.search(r"PASSED:\s*(\d+)\s+FAILED:\s*(\d+)\s+SKIPPED:\s*(\d+)", content)
        if m:
            passed = int(m.group(1))
            failed = int(m.group(2))
            skipped = int(m.group(3))
        else:
            # Backward compat: old logs without SKIPPED field
            m2 = re.search(r"PASSED:\s*(\d+)\s+FAILED:\s*(\d+)", content)
            if m2:
                passed = int(m2.group(1))
                failed = int(m2.group(2))

    except Exception as exc:
        return {
            "step": step_name,
            "passed": 0,
            "failed": 0,
            "skipped": 0,
            "total": 0,
            "pct": 0.0,
            "status": f"ERROR ({exc})",
        }

    total = passed + failed + skipped
    pct = (passed / total * 100) if total > 0 else 0.0

    if failed == 0 and total > 0:
        status = "PASS"
    elif failed > 0 and passed == 0:
        status = "FAIL"
    elif failed > 0:
        status = "PARTIAL"
    else:
        status = "NO_TESTS"

    return {
        "step": step_name,
        "passed": passed,
        "failed": failed,
        "skipped": skipped,
        "total": total,
        "pct": pct,
        "status": status,
    }


def generate_report(logs_dir: str = LOGS_DIR) -> str:
    """Generate the full Markdown report content."""
    log_files = sorted(
        f for f in os.listdir(logs_dir)
        if f.endswith(".log") and not f.startswith(".")
    )

    results = [parse_log_file(os.path.join(logs_dir, f)) for f in log_files]

    timestamp = datetime.datetime.now().isoformat(timespec="seconds")
    total_passed  = sum(r["passed"] for r in results)
    total_failed  = sum(r["failed"] for r in results)
    total_skipped = sum(r["skipped"] for r in results)
    total_all     = total_passed + total_failed + total_skipped
    overall_pct   = (total_passed / total_all * 100) if total_all > 0 else 0.0

    lines = [
        "# UAT Report — ReportAutomatization (RA)",
        "",
        f"Generated: {timestamp}",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total steps executed | {len(results)} |",
        f"| Total assertions | {total_all} |",
        f"| Passed | {total_passed} |",
        f"| Failed | {total_failed} |",
        f"| Skipped (missing features) | {total_skipped} |",
        f"| Overall success rate | {overall_pct:.1f}% |",
        "",
        "## Step Results",
        "",
        "| Step | Total | Passed | Failed | Skipped | Success% | Status |",
        "|------|-------|--------|--------|---------|----------|--------|",
    ]

    for r in results:
        pct_str = f"{r['pct']:.0f}%"
        status_badge = {
            "PASS": "PASS",
            "FAIL": "FAIL",
            "PARTIAL": "PARTIAL",
            "NO_TESTS": "EMPTY",
        }.get(r["status"], r["status"])

        lines.append(
            f"| {r['step']} | {r['total']} | {r['passed']} | {r['failed']} "
            f"| {r['skipped']} | {pct_str} | {status_badge} |"
        )

    # Error files section
    error_files = sorted(
        f for f in os.listdir(logs_dir)
        if f.endswith("_errors.md")
    )

    if error_files:
        lines += [
            "",
            "## Error Details",
            "",
            "The following steps produced error reports:",
            "",
        ]
        for ef in error_files:
            step = ef.replace("_errors.md", "")
            lines.append(f"- [{step}]({ef})")

    lines += [
        "",
        "---",
        "",
        "_Report generated by `shared/report_generator.py`_",
        "",
    ]

    return "\n".join(lines)


def main() -> None:
    logs_dir = sys.argv[1] if len(sys.argv) > 1 else LOGS_DIR

    if not os.path.isdir(logs_dir):
        print(f"ERROR: logs directory not found: {logs_dir}", file=sys.stderr)
        sys.exit(1)

    report = generate_report(logs_dir)
    report_path = os.path.join(logs_dir, "UAT_REPORT.md")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print(report)
    print(f"\n[INFO] Report saved to: {report_path}")


if __name__ == "__main__":
    main()
